package modelo.entidad;
// Generated 06-oct-2018 13:52:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer idequipo;
     private Estado estado;
     private Marca marca;
     private String tipo;
     private String modelo;
     private String serie;
     private Date fechaIngreso;
     private Double precio;
     private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);
     private Set<Mantenimiento> mantenimientos = new HashSet<Mantenimiento>(0);

    public Equipo() {
    }

    public Equipo(Estado estado, Marca marca, String tipo, String modelo, String serie, Date fechaIngreso, Double precio, Set<Movimiento> movimientos, Set<Mantenimiento> mantenimientos) {
       this.estado = estado;
       this.marca = marca;
       this.tipo = tipo;
       this.modelo = modelo;
       this.serie = serie;
       this.fechaIngreso = fechaIngreso;
       this.precio = precio;
       this.movimientos = movimientos;
       this.mantenimientos = mantenimientos;
    }
   
    public Integer getIdequipo() {
        return this.idequipo;
    }
    
    public void setIdequipo(Integer idequipo) {
        this.idequipo = idequipo;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Set<Movimiento> getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set<Movimiento> movimientos) {
        this.movimientos = movimientos;
    }
    public Set<Mantenimiento> getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(Set<Mantenimiento> mantenimientos) {
        this.mantenimientos = mantenimientos;
    }




}


