package modelo.entidad;
// Generated 06-oct-2018 13:52:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private Integer idestado;
     private String estado;
     private Set<Equipo> equipos = new HashSet<Equipo>(0);

    public Estado() {
    }

    public Estado(String estado, Set<Equipo> equipos) {
       this.estado = estado;
       this.equipos = equipos;
    }
   
    public Integer getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }




}


