package modelo.entidad;
// Generated 06-oct-2018 13:52:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mantenimiento generated by hbm2java
 */
public class Mantenimiento  implements java.io.Serializable {


     private Integer idmantenimiento;
     private Equipo equipo;
     private Usuario usuario;
     private Integer tipo;
     private Date fecha;

    public Mantenimiento() {
        // para los combos
        equipo = new Equipo();
        usuario = new Usuario();
    }

    public Mantenimiento(Equipo equipo, Usuario usuario, Integer tipo, Date fecha) {
       this.equipo = equipo;
       this.usuario = usuario;
       this.tipo = tipo;
       this.fecha = fecha;
    }
   
    public Integer getIdmantenimiento() {
        return this.idmantenimiento;
    }
    
    public void setIdmantenimiento(Integer idmantenimiento) {
        this.idmantenimiento = idmantenimiento;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


