package modelo.entidad;
// Generated 06-oct-2018 13:52:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private Integer idmarca;
     private String marca;
     private Set<Equipo> equipos = new HashSet<Equipo>(0);

    public Marca() {
    }

    public Marca(String marca, Set<Equipo> equipos) {
       this.marca = marca;
       this.equipos = equipos;
    }
   
    public Integer getIdmarca() {
        return this.idmarca;
    }
    
    public void setIdmarca(Integer idmarca) {
        this.idmarca = idmarca;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }




}


