package modelo.entidad;
// Generated 06-oct-2018 13:52:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento  implements java.io.Serializable {


     private Integer idmovimiento;
     private Empleado empleado;
     private Equipo equipo;
     private Usuario usuario;
     private Date fechaAsignacion;
     private Integer tipoMovimiento;

    public Movimiento() {
    }

    public Movimiento(Empleado empleado, Equipo equipo, Usuario usuario, Date fechaAsignacion, Integer tipoMovimiento) {
       this.empleado = empleado;
       this.equipo = equipo;
       this.usuario = usuario;
       this.fechaAsignacion = fechaAsignacion;
       this.tipoMovimiento = tipoMovimiento;
    }
   
    public Integer getIdmovimiento() {
        return this.idmovimiento;
    }
    
    public void setIdmovimiento(Integer idmovimiento) {
        this.idmovimiento = idmovimiento;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaAsignacion() {
        return this.fechaAsignacion;
    }
    
    public void setFechaAsignacion(Date fechaAsignacion) {
        this.fechaAsignacion = fechaAsignacion;
    }
    public Integer getTipoMovimiento() {
        return this.tipoMovimiento;
    }
    
    public void setTipoMovimiento(Integer tipoMovimiento) {
        this.tipoMovimiento = tipoMovimiento;
    }




}


