package modelo.entidad;
// Generated 06-oct-2018 13:52:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private String nombre;
     private String apellido;
     private String user;
     private String password;
     private Date fechaCreacion;
     private Set<Mantenimiento> mantenimientos = new HashSet<Mantenimiento>(0);
     private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

    public Usuario() {
    }

    public Usuario(String nombre, String apellido, String user, String password, Date fechaCreacion, Set<Mantenimiento> mantenimientos, Set<Movimiento> movimientos) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.user = user;
       this.password = password;
       this.fechaCreacion = fechaCreacion;
       this.mantenimientos = mantenimientos;
       this.movimientos = movimientos;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Set<Mantenimiento> getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(Set<Mantenimiento> mantenimientos) {
        this.mantenimientos = mantenimientos;
    }
    public Set<Movimiento> getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set<Movimiento> movimientos) {
        this.movimientos = movimientos;
    }




}


